name: CI - Build & Push to ECR

on:
  push:
    branches:
      - dev
      - master

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Gradle 실행 권한 부여
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Set Role ARN by branch
        run: |
          if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            echo "ROLE_ARN=arn:aws:iam::092504162781:role/gh-actions-deploy-stg" >> $GITHUB_ENV
          else
            echo "ROLE_ARN=arn:aws:iam::092504162781:role/gh-actions-deploy-prod" >> $GITHUB_ENV
          fi

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: groute-ecr
          IMAGE_TAG: sha-${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "Pushed → $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"